name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: validate before release
        run: |
          npm install --no-save
          npm run lint
          npm run test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
